<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Waves\Protobuf\InvokeScriptResult\Lease instead.
     * @deprecated
     */
    class InvokeScriptResult_Lease {}
}
class_exists(InvokeScriptResult\Lease::class);
@trigger_error('Waves\Protobuf\InvokeScriptResult_Lease is deprecated and will be removed in the next major release. Use Waves\Protobuf\InvokeScriptResult\Lease instead', E_USER_DEPRECATED);

