<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Waves\Protobuf\InvokeScriptResult\Call\Argument instead.
     * @deprecated
     */
    class InvokeScriptResult_Call_Argument {}
}
class_exists(InvokeScriptResult\Call\Argument::class);
@trigger_error('Waves\Protobuf\InvokeScriptResult_Call_Argument is deprecated and will be removed in the next major release. Use Waves\Protobuf\InvokeScriptResult\Call\Argument instead', E_USER_DEPRECATED);

