<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/state_snapshot.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.MicroBlockSnapshot</code>
 */
class MicroBlockSnapshot extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes total_block_id = 1;</code>
     */
    protected $total_block_id = '';
    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot snapshots = 2;</code>
     */
    private $snapshots;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $total_block_id
     *     @type array<\Waves\Protobuf\TransactionStateSnapshot>|\Google\Protobuf\Internal\RepeatedField $snapshots
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\StateSnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes total_block_id = 1;</code>
     * @return string
     */
    public function getTotalBlockId()
    {
        return $this->total_block_id;
    }

    /**
     * Generated from protobuf field <code>bytes total_block_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalBlockId($var)
    {
        GPBUtil::checkString($var, False);
        $this->total_block_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot snapshots = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSnapshots()
    {
        return $this->snapshots;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.TransactionStateSnapshot snapshots = 2;</code>
     * @param array<\Waves\Protobuf\TransactionStateSnapshot>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSnapshots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Protobuf\TransactionStateSnapshot::class);
        $this->snapshots = $arr;

        return $this;
    }

}

