<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/order.proto

namespace Waves\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Waves\Protobuf\Order\Side instead.
     * @deprecated
     */
    class Order_Side {}
}
class_exists(Order\Side::class);
@trigger_error('Waves\Protobuf\Order_Side is deprecated and will be removed in the next major release. Use Waves\Protobuf\Order\Side instead', E_USER_DEPRECATED);

