<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/reward_share.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.RewardShare</code>
 */
class RewardShare extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>int64 reward = 2;</code>
     */
    protected $reward = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type int|string $reward
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\RewardShare::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reward = 2;</code>
     * @return int|string
     */
    public function getReward()
    {
        return $this->reward;
    }

    /**
     * Generated from protobuf field <code>int64 reward = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReward($var)
    {
        GPBUtil::checkInt64($var);
        $this->reward = $var;

        return $this;
    }

}

