<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/transaction_state_snapshot.proto

namespace Waves\Protobuf;

use UnexpectedValueException;

/**
 * Protobuf type <code>waves.TransactionStatus</code>
 */
class TransactionStatus
{
    /**
     * Generated from protobuf enum <code>SUCCEEDED = 0;</code>
     */
    const SUCCEEDED = 0;
    /**
     * Generated from protobuf enum <code>FAILED = 1;</code>
     */
    const FAILED = 1;
    /**
     * Generated from protobuf enum <code>ELIDED = 2;</code>
     */
    const ELIDED = 2;

    private static $valueToName = [
        self::SUCCEEDED => 'SUCCEEDED',
        self::FAILED => 'FAILED',
        self::ELIDED => 'ELIDED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

