<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/transaction.proto

namespace Waves\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 chain_id = 1;</code>
     */
    protected $chain_id = 0;
    /**
     * Generated from protobuf field <code>bytes sender_public_key = 2;</code>
     */
    protected $sender_public_key = '';
    /**
     * Generated from protobuf field <code>.waves.Amount fee = 3;</code>
     */
    protected $fee = null;
    /**
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>int32 version = 5;</code>
     */
    protected $version = 0;
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $chain_id
     *     @type string $sender_public_key
     *     @type \Waves\Protobuf\Amount $fee
     *     @type int|string $timestamp
     *     @type int $version
     *     @type \Waves\Protobuf\GenesisTransactionData $genesis
     *     @type \Waves\Protobuf\PaymentTransactionData $payment
     *     @type \Waves\Protobuf\IssueTransactionData $issue
     *     @type \Waves\Protobuf\TransferTransactionData $transfer
     *     @type \Waves\Protobuf\ReissueTransactionData $reissue
     *     @type \Waves\Protobuf\BurnTransactionData $burn
     *     @type \Waves\Protobuf\ExchangeTransactionData $exchange
     *     @type \Waves\Protobuf\LeaseTransactionData $lease
     *     @type \Waves\Protobuf\LeaseCancelTransactionData $lease_cancel
     *     @type \Waves\Protobuf\CreateAliasTransactionData $create_alias
     *     @type \Waves\Protobuf\MassTransferTransactionData $mass_transfer
     *     @type \Waves\Protobuf\DataTransactionData $data_transaction
     *     @type \Waves\Protobuf\SetScriptTransactionData $set_script
     *     @type \Waves\Protobuf\SponsorFeeTransactionData $sponsor_fee
     *     @type \Waves\Protobuf\SetAssetScriptTransactionData $set_asset_script
     *     @type \Waves\Protobuf\InvokeScriptTransactionData $invoke_script
     *     @type \Waves\Protobuf\UpdateAssetInfoTransactionData $update_asset_info
     *     @type \Waves\Protobuf\InvokeExpressionTransactionData $invoke_expression
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 chain_id = 1;</code>
     * @return int
     */
    public function getChainId()
    {
        return $this->chain_id;
    }

    /**
     * Generated from protobuf field <code>int32 chain_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setChainId($var)
    {
        GPBUtil::checkInt32($var);
        $this->chain_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 2;</code>
     * @return string
     */
    public function getSenderPublicKey()
    {
        return $this->sender_public_key;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSenderPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->sender_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.Amount fee = 3;</code>
     * @return \Waves\Protobuf\Amount|null
     */
    public function getFee()
    {
        return $this->fee;
    }

    public function hasFee()
    {
        return isset($this->fee);
    }

    public function clearFee()
    {
        unset($this->fee);
    }

    /**
     * Generated from protobuf field <code>.waves.Amount fee = 3;</code>
     * @param \Waves\Protobuf\Amount $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\Amount::class);
        $this->fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version = 5;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.GenesisTransactionData genesis = 101;</code>
     * @return \Waves\Protobuf\GenesisTransactionData|null
     */
    public function getGenesis()
    {
        return $this->readOneof(101);
    }

    public function hasGenesis()
    {
        return $this->hasOneof(101);
    }

    /**
     * Generated from protobuf field <code>.waves.GenesisTransactionData genesis = 101;</code>
     * @param \Waves\Protobuf\GenesisTransactionData $var
     * @return $this
     */
    public function setGenesis($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\GenesisTransactionData::class);
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.PaymentTransactionData payment = 102;</code>
     * @return \Waves\Protobuf\PaymentTransactionData|null
     */
    public function getPayment()
    {
        return $this->readOneof(102);
    }

    public function hasPayment()
    {
        return $this->hasOneof(102);
    }

    /**
     * Generated from protobuf field <code>.waves.PaymentTransactionData payment = 102;</code>
     * @param \Waves\Protobuf\PaymentTransactionData $var
     * @return $this
     */
    public function setPayment($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\PaymentTransactionData::class);
        $this->writeOneof(102, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.IssueTransactionData issue = 103;</code>
     * @return \Waves\Protobuf\IssueTransactionData|null
     */
    public function getIssue()
    {
        return $this->readOneof(103);
    }

    public function hasIssue()
    {
        return $this->hasOneof(103);
    }

    /**
     * Generated from protobuf field <code>.waves.IssueTransactionData issue = 103;</code>
     * @param \Waves\Protobuf\IssueTransactionData $var
     * @return $this
     */
    public function setIssue($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\IssueTransactionData::class);
        $this->writeOneof(103, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.TransferTransactionData transfer = 104;</code>
     * @return \Waves\Protobuf\TransferTransactionData|null
     */
    public function getTransfer()
    {
        return $this->readOneof(104);
    }

    public function hasTransfer()
    {
        return $this->hasOneof(104);
    }

    /**
     * Generated from protobuf field <code>.waves.TransferTransactionData transfer = 104;</code>
     * @param \Waves\Protobuf\TransferTransactionData $var
     * @return $this
     */
    public function setTransfer($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\TransferTransactionData::class);
        $this->writeOneof(104, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.ReissueTransactionData reissue = 105;</code>
     * @return \Waves\Protobuf\ReissueTransactionData|null
     */
    public function getReissue()
    {
        return $this->readOneof(105);
    }

    public function hasReissue()
    {
        return $this->hasOneof(105);
    }

    /**
     * Generated from protobuf field <code>.waves.ReissueTransactionData reissue = 105;</code>
     * @param \Waves\Protobuf\ReissueTransactionData $var
     * @return $this
     */
    public function setReissue($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\ReissueTransactionData::class);
        $this->writeOneof(105, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.BurnTransactionData burn = 106;</code>
     * @return \Waves\Protobuf\BurnTransactionData|null
     */
    public function getBurn()
    {
        return $this->readOneof(106);
    }

    public function hasBurn()
    {
        return $this->hasOneof(106);
    }

    /**
     * Generated from protobuf field <code>.waves.BurnTransactionData burn = 106;</code>
     * @param \Waves\Protobuf\BurnTransactionData $var
     * @return $this
     */
    public function setBurn($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\BurnTransactionData::class);
        $this->writeOneof(106, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.ExchangeTransactionData exchange = 107;</code>
     * @return \Waves\Protobuf\ExchangeTransactionData|null
     */
    public function getExchange()
    {
        return $this->readOneof(107);
    }

    public function hasExchange()
    {
        return $this->hasOneof(107);
    }

    /**
     * Generated from protobuf field <code>.waves.ExchangeTransactionData exchange = 107;</code>
     * @param \Waves\Protobuf\ExchangeTransactionData $var
     * @return $this
     */
    public function setExchange($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\ExchangeTransactionData::class);
        $this->writeOneof(107, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.LeaseTransactionData lease = 108;</code>
     * @return \Waves\Protobuf\LeaseTransactionData|null
     */
    public function getLease()
    {
        return $this->readOneof(108);
    }

    public function hasLease()
    {
        return $this->hasOneof(108);
    }

    /**
     * Generated from protobuf field <code>.waves.LeaseTransactionData lease = 108;</code>
     * @param \Waves\Protobuf\LeaseTransactionData $var
     * @return $this
     */
    public function setLease($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\LeaseTransactionData::class);
        $this->writeOneof(108, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.LeaseCancelTransactionData lease_cancel = 109;</code>
     * @return \Waves\Protobuf\LeaseCancelTransactionData|null
     */
    public function getLeaseCancel()
    {
        return $this->readOneof(109);
    }

    public function hasLeaseCancel()
    {
        return $this->hasOneof(109);
    }

    /**
     * Generated from protobuf field <code>.waves.LeaseCancelTransactionData lease_cancel = 109;</code>
     * @param \Waves\Protobuf\LeaseCancelTransactionData $var
     * @return $this
     */
    public function setLeaseCancel($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\LeaseCancelTransactionData::class);
        $this->writeOneof(109, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.CreateAliasTransactionData create_alias = 110;</code>
     * @return \Waves\Protobuf\CreateAliasTransactionData|null
     */
    public function getCreateAlias()
    {
        return $this->readOneof(110);
    }

    public function hasCreateAlias()
    {
        return $this->hasOneof(110);
    }

    /**
     * Generated from protobuf field <code>.waves.CreateAliasTransactionData create_alias = 110;</code>
     * @param \Waves\Protobuf\CreateAliasTransactionData $var
     * @return $this
     */
    public function setCreateAlias($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\CreateAliasTransactionData::class);
        $this->writeOneof(110, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.MassTransferTransactionData mass_transfer = 111;</code>
     * @return \Waves\Protobuf\MassTransferTransactionData|null
     */
    public function getMassTransfer()
    {
        return $this->readOneof(111);
    }

    public function hasMassTransfer()
    {
        return $this->hasOneof(111);
    }

    /**
     * Generated from protobuf field <code>.waves.MassTransferTransactionData mass_transfer = 111;</code>
     * @param \Waves\Protobuf\MassTransferTransactionData $var
     * @return $this
     */
    public function setMassTransfer($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\MassTransferTransactionData::class);
        $this->writeOneof(111, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.DataTransactionData data_transaction = 112;</code>
     * @return \Waves\Protobuf\DataTransactionData|null
     */
    public function getDataTransaction()
    {
        return $this->readOneof(112);
    }

    public function hasDataTransaction()
    {
        return $this->hasOneof(112);
    }

    /**
     * Generated from protobuf field <code>.waves.DataTransactionData data_transaction = 112;</code>
     * @param \Waves\Protobuf\DataTransactionData $var
     * @return $this
     */
    public function setDataTransaction($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\DataTransactionData::class);
        $this->writeOneof(112, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.SetScriptTransactionData set_script = 113;</code>
     * @return \Waves\Protobuf\SetScriptTransactionData|null
     */
    public function getSetScript()
    {
        return $this->readOneof(113);
    }

    public function hasSetScript()
    {
        return $this->hasOneof(113);
    }

    /**
     * Generated from protobuf field <code>.waves.SetScriptTransactionData set_script = 113;</code>
     * @param \Waves\Protobuf\SetScriptTransactionData $var
     * @return $this
     */
    public function setSetScript($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\SetScriptTransactionData::class);
        $this->writeOneof(113, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.SponsorFeeTransactionData sponsor_fee = 114;</code>
     * @return \Waves\Protobuf\SponsorFeeTransactionData|null
     */
    public function getSponsorFee()
    {
        return $this->readOneof(114);
    }

    public function hasSponsorFee()
    {
        return $this->hasOneof(114);
    }

    /**
     * Generated from protobuf field <code>.waves.SponsorFeeTransactionData sponsor_fee = 114;</code>
     * @param \Waves\Protobuf\SponsorFeeTransactionData $var
     * @return $this
     */
    public function setSponsorFee($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\SponsorFeeTransactionData::class);
        $this->writeOneof(114, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.SetAssetScriptTransactionData set_asset_script = 115;</code>
     * @return \Waves\Protobuf\SetAssetScriptTransactionData|null
     */
    public function getSetAssetScript()
    {
        return $this->readOneof(115);
    }

    public function hasSetAssetScript()
    {
        return $this->hasOneof(115);
    }

    /**
     * Generated from protobuf field <code>.waves.SetAssetScriptTransactionData set_asset_script = 115;</code>
     * @param \Waves\Protobuf\SetAssetScriptTransactionData $var
     * @return $this
     */
    public function setSetAssetScript($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\SetAssetScriptTransactionData::class);
        $this->writeOneof(115, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptTransactionData invoke_script = 116;</code>
     * @return \Waves\Protobuf\InvokeScriptTransactionData|null
     */
    public function getInvokeScript()
    {
        return $this->readOneof(116);
    }

    public function hasInvokeScript()
    {
        return $this->hasOneof(116);
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptTransactionData invoke_script = 116;</code>
     * @param \Waves\Protobuf\InvokeScriptTransactionData $var
     * @return $this
     */
    public function setInvokeScript($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\InvokeScriptTransactionData::class);
        $this->writeOneof(116, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.UpdateAssetInfoTransactionData update_asset_info = 117;</code>
     * @return \Waves\Protobuf\UpdateAssetInfoTransactionData|null
     */
    public function getUpdateAssetInfo()
    {
        return $this->readOneof(117);
    }

    public function hasUpdateAssetInfo()
    {
        return $this->hasOneof(117);
    }

    /**
     * Generated from protobuf field <code>.waves.UpdateAssetInfoTransactionData update_asset_info = 117;</code>
     * @param \Waves\Protobuf\UpdateAssetInfoTransactionData $var
     * @return $this
     */
    public function setUpdateAssetInfo($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\UpdateAssetInfoTransactionData::class);
        $this->writeOneof(117, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeExpressionTransactionData invoke_expression = 119;</code>
     * @return \Waves\Protobuf\InvokeExpressionTransactionData|null
     */
    public function getInvokeExpression()
    {
        return $this->readOneof(119);
    }

    public function hasInvokeExpression()
    {
        return $this->hasOneof(119);
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeExpressionTransactionData invoke_expression = 119;</code>
     * @param \Waves\Protobuf\InvokeExpressionTransactionData $var
     * @return $this
     */
    public function setInvokeExpression($var)
    {
        GPBUtil::checkMessage($var, \Waves\Protobuf\InvokeExpressionTransactionData::class);
        $this->writeOneof(119, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

