<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/order.proto

namespace Waves\Protobuf\Order;

use UnexpectedValueException;

/**
 * Protobuf type <code>waves.Order.PriceMode</code>
 */
class PriceMode
{
    /**
     * Generated from protobuf enum <code>DEFAULT = 0;</code>
     */
    const PBDEFAULT = 0;
    /**
     * Generated from protobuf enum <code>FIXED_DECIMALS = 1;</code>
     */
    const FIXED_DECIMALS = 1;
    /**
     * Generated from protobuf enum <code>ASSET_DECIMALS = 2;</code>
     */
    const ASSET_DECIMALS = 2;

    private static $valueToName = [
        self::PBDEFAULT => 'DEFAULT',
        self::FIXED_DECIMALS => 'FIXED_DECIMALS',
        self::ASSET_DECIMALS => 'ASSET_DECIMALS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', __CLASS__, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

