<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/block.proto

namespace Waves\ProtobufMetadata;

class Block
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Waves\ProtobufMetadata\Transaction::initOnce();
        $pool->internalAddGeneratedFile(
            '
ç
waves/block.protowaves"–
Block#
header (2.waves.Block.Header
	signature (.
transactions (2.waves.SignedTransactionﬁ
Header
chain_id (
	reference (
base_target (
generation_signature (
feature_votes (
	timestamp (
version (
	generator (
reward_vote	 (
transactions_root
 ("ú

MicroBlock
version (
	reference (
updated_block_signature (
sender_public_key (.
transactions (2.waves.SignedTransaction"e
SignedMicroBlock&
micro_block (2.waves.MicroBlock
	signature (
total_block_id (Bè
 com.wavesplatform.protobuf.blockZ9github.com/wavesplatform/gowaves/pkg/grpc/generated/waves™Waves Waves\\Protobuf‚Waves\\ProtobufMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

