<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/state_snapshot.proto

namespace Waves\ProtobufMetadata;

class StateSnapshot
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Waves\ProtobufMetadata\TransactionStateSnapshot::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF9\x02\x0A\x1Awaves/state_snapshot.proto\x12\x05waves\"U\x0A\x0DBlockSnapshot\x12\x10\x0A\x08block_id\x18\x01 \x01(\x0C\x122\x0A\x09snapshots\x18\x02 \x03(\x0B2\x1F.waves.TransactionStateSnapshot\"`\x0A\x12MicroBlockSnapshot\x12\x16\x0A\x0Etotal_block_id\x18\x01 \x01(\x0C\x122\x0A\x09snapshots\x18\x02 \x03(\x0B2\x1F.waves.TransactionStateSnapshotB\x92\x01\x0A#com.wavesplatform.protobuf.snapshotZ9github.com/wavesplatform/gowaves/pkg/grpc/generated/waves\xAA\x02\x05Waves\xCA\x02\x0EWaves\\Protobuf\xE2\x02\x16Waves\\ProtobufMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

