<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/transaction_state_snapshot.proto

namespace Waves\Protobuf\TransactionStateSnapshot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.TransactionStateSnapshot.AccountScript</code>
 */
class AccountScript extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes sender_public_key = 1;</code>
     */
    protected $sender_public_key = '';
    /**
     * Generated from protobuf field <code>bytes script = 2;</code>
     */
    protected $script = '';
    /**
     * Generated from protobuf field <code>int64 verifier_complexity = 3;</code>
     */
    protected $verifier_complexity = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sender_public_key
     *     @type string $script
     *     @type int|string $verifier_complexity
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\TransactionStateSnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 1;</code>
     * @return string
     */
    public function getSenderPublicKey()
    {
        return $this->sender_public_key;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSenderPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->sender_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes script = 2;</code>
     * @return string
     */
    public function getScript()
    {
        return $this->script;
    }

    /**
     * Generated from protobuf field <code>bytes script = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setScript($var)
    {
        GPBUtil::checkString($var, False);
        $this->script = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 verifier_complexity = 3;</code>
     * @return int|string
     */
    public function getVerifierComplexity()
    {
        return $this->verifier_complexity;
    }

    /**
     * Generated from protobuf field <code>int64 verifier_complexity = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVerifierComplexity($var)
    {
        GPBUtil::checkInt64($var);
        $this->verifier_complexity = $var;

        return $this;
    }

}

