<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/transaction_state_snapshot.proto

namespace Waves\Protobuf\TransactionStateSnapshot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.TransactionStateSnapshot.LeaseBalance</code>
 */
class LeaseBalance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>int64 in = 2;</code>
     */
    protected $in = 0;
    /**
     * Generated from protobuf field <code>int64 out = 3;</code>
     */
    protected $out = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type int|string $in
     *     @type int|string $out
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\TransactionStateSnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 in = 2;</code>
     * @return int|string
     */
    public function getIn()
    {
        return $this->in;
    }

    /**
     * Generated from protobuf field <code>int64 in = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIn($var)
    {
        GPBUtil::checkInt64($var);
        $this->in = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 out = 3;</code>
     * @return int|string
     */
    public function getOut()
    {
        return $this->out;
    }

    /**
     * Generated from protobuf field <code>int64 out = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOut($var)
    {
        GPBUtil::checkInt64($var);
        $this->out = $var;

        return $this;
    }

}

