<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waves/transaction_state_snapshot.proto

namespace Waves\Protobuf\TransactionStateSnapshot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.TransactionStateSnapshot.NewAsset</code>
 */
class NewAsset extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes asset_id = 1;</code>
     */
    protected $asset_id = '';
    /**
     * Generated from protobuf field <code>bytes issuer_public_key = 2;</code>
     */
    protected $issuer_public_key = '';
    /**
     * Generated from protobuf field <code>int32 decimals = 3;</code>
     */
    protected $decimals = 0;
    /**
     * Generated from protobuf field <code>bool nft = 4;</code>
     */
    protected $nft = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $asset_id
     *     @type string $issuer_public_key
     *     @type int $decimals
     *     @type bool $nft
     * }
     */
    public function __construct($data = NULL) {
        \Waves\ProtobufMetadata\TransactionStateSnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes asset_id = 1;</code>
     * @return string
     */
    public function getAssetId()
    {
        return $this->asset_id;
    }

    /**
     * Generated from protobuf field <code>bytes asset_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAssetId($var)
    {
        GPBUtil::checkString($var, False);
        $this->asset_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes issuer_public_key = 2;</code>
     * @return string
     */
    public function getIssuerPublicKey()
    {
        return $this->issuer_public_key;
    }

    /**
     * Generated from protobuf field <code>bytes issuer_public_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIssuerPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->issuer_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 decimals = 3;</code>
     * @return int
     */
    public function getDecimals()
    {
        return $this->decimals;
    }

    /**
     * Generated from protobuf field <code>int32 decimals = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDecimals($var)
    {
        GPBUtil::checkInt32($var);
        $this->decimals = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool nft = 4;</code>
     * @return bool
     */
    public function getNft()
    {
        return $this->nft;
    }

    /**
     * Generated from protobuf field <code>bool nft = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setNft($var)
    {
        GPBUtil::checkBool($var);
        $this->nft = $var;

        return $this;
    }

}

